### ISSUE TITLE
Plugin isnt working on Paper 1.20.6

### ISSUE THREAD

**Issue by Scrulius** [Awoo-industries/BetterKeepInventory#131]
Hello! 

I love your plugin and use it for a long time, in 1.20.6 it stopped working, it would be great if you update it!

Thanks uwu

[10:47:06] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to BetterKeepInventory v1.5
java.lang.IllegalArgumentException: No enum constant dev.beeps.plugins.BetterConfig.ItemMode.percentage
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:54) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.BetterConfig$ItemMode.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(BetterConfig.java) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.BetterConfig$ItemMode.valueOf(BetterConfig.java:26) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.BetterConfig.getItemMode(BetterConfig.java:305) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.Events.Types.ItemHandler.<init>(ItemHandler.java:35) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.Events.OnPlayerDeath.handleItems(OnPlayerDeath.java:153) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.Events.OnPlayerDeath.onPlayerDeath(OnPlayerDeath.java:89) ~[BetterKeepInventory-1.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor832.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-129-0513374]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1020) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1046) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at org.bukkit.craftbukkit.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:121) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:37) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.commands.EssentialsLoopCommand.lambda$loopOnlinePlayers$1(EssentialsLoopCommand.java:72) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayersConsumer(EssentialsLoopCommand.java:115) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:72) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:23) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:885) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at EssentialsX-2.21.0-dev+91-e7a4167.jar/com.earth2me.essentials.Essentials.onCommand(Essentials.java:786) ~[EssentialsX-2.21.0-dev+91-e7a4167.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:964) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:949) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:47:06] [Server thread/INFO]: $<p:prefix> Eliminado <p:primary-color>Melonzio</p>.
[10:47:58] [Server thread/INFO]: Invalid subcommand
[10:48:00] [Server thread/INFO]: Reloaded!
[10:48:08] [Server thread/INFO]: [Essentials] CONSOLE issued server command: /give Melonzio diamondpick 1
[10:48:08] [Server thread/INFO]: $<p:prefix> Dando <p:primary-color>1</p> de <p:primary-color>diamond pickaxe</p> a <p:primary-color>Melonzio</p>.
[10:48:47] [Server thread/INFO]: [Essentials] CommandBlock at -303,105,910 issued server command: /day set day Spawn
[10:48:58] [Server thread/INFO]: Melonzio fue tragado por el abismo
[10:48:58] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to BetterKeepInventory v1.5
java.lang.IllegalArgumentException: No enum constant dev.beeps.plugins.BetterConfig.ItemMode.percentage
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:54) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.BetterConfig$ItemMode.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(BetterConfig.java) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.BetterConfig$ItemMode.valueOf(BetterConfig.java:26) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.BetterConfig.getItemMode(BetterConfig.java:305) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.Events.Types.ItemHandler.<init>(ItemHandler.java:35) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.Events.OnPlayerDeath.handleItems(OnPlayerDeath.java:153) ~[BetterKeepInventory-1.5.jar:?]
	at BetterKeepInventory-1.5.jar/dev.beeps.plugins.Events.OnPlayerDeath.onPlayerDeath(OnPlayerDeath.java:89) ~[BetterKeepInventory-1.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor832.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-129-0513374]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1020) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1046) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1584) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:986) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1213) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.LivingEntity.onBelowWorld(LivingEntity.java:2579) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.Entity.checkBelowWorld(Entity.java:953) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:934) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:420) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.Entity.tick(Entity.java:866) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3080) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.world.entity.player.Player.tick(Player.java:286) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:845) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.network.Connection.tick(Connection.java:630) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-129-0513374]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BeepSterr** [comment]
Heya, Looks like you set the item mode to an invalid value, remember that it should always be fully capitalized with no spaces or anything

it should look like this: 
``` mode: "PERCENTAGE"```

I do admit this is a little stupid, so i'm gonna include a fix for that in the next version ^^

**Comment by BeepSterr** [comment]
Closing this for now, if you're still having issues please reopen!
